// This file is automatically generated by qtc from "index.html".
// See https://github.com/valyala/quicktemplate for details.

//line web/views/index.html:1
package views

//line web/views/index.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line web/views/index.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line web/views/index.html:1
func StreamIndex(qw422016 *qt422016.Writer, log string) {
	//line web/views/index.html:1
	qw422016.N().S(`
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Translator</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            `)
	//line web/views/index.html:10
	StreamMaterialize(qw422016)
	//line web/views/index.html:10
	qw422016.N().S(`   
            `)
	//line web/views/index.html:11
	StreamStyle(qw422016)
	//line web/views/index.html:11
	qw422016.N().S(`              
        </style>
        <script>
            `)
	//line web/views/index.html:14
	StreamJquery(qw422016)
	//line web/views/index.html:14
	qw422016.N().S(`        
            `)
	//line web/views/index.html:15
	StreamMaterializeJS(qw422016)
	//line web/views/index.html:15
	qw422016.N().S(`   
            `)
	//line web/views/index.html:16
	StreamJs(qw422016)
	//line web/views/index.html:16
	qw422016.N().S(`        
        </script>
    </head>
    <body>
        <div class="row">
            <div class="col s12">
                <div class="card indigo lighten-4">
                <div class="card-content">
                    <div class="row">
                        <form action="/" method="POST">
                            <div class="col s12">
                                    <div class="input-field col s12">
                                        <select name="kan">
                                            <option value="" disabled selected>Choose your option</option>
                                            <option value="0">Indonesia - English</option>
                                            <option value="1">English - Indonesia</option>
                                        </select>
                                        <label class="indigo-text">Language</label>
                                    </div>
                                    <textarea class="id" name="id" cols="50" rows="50"></textarea>        
                                </div>
                                <input type="submit" name="submit" value="Terjemahkan">                
                        </form>
                    </div>
                Created @2018-2019
                by iqbal & Hafid
                </div>
                </div>
            </div>
            </div>
        <div>
        `)
	//line web/views/index.html:47
	StreamLog(qw422016, log)
	//line web/views/index.html:47
	qw422016.N().S(`
    </body>
    </html>
`)
//line web/views/index.html:50
}

//line web/views/index.html:50
func WriteIndex(qq422016 qtio422016.Writer, log string) {
	//line web/views/index.html:50
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line web/views/index.html:50
	StreamIndex(qw422016, log)
	//line web/views/index.html:50
	qt422016.ReleaseWriter(qw422016)
//line web/views/index.html:50
}

//line web/views/index.html:50
func Index(log string) string {
	//line web/views/index.html:50
	qb422016 := qt422016.AcquireByteBuffer()
	//line web/views/index.html:50
	WriteIndex(qb422016, log)
	//line web/views/index.html:50
	qs422016 := string(qb422016.B)
	//line web/views/index.html:50
	qt422016.ReleaseByteBuffer(qb422016)
	//line web/views/index.html:50
	return qs422016
//line web/views/index.html:50
}

// <div> Inggris </div>
// <textarea class="en" name="en" cols="30" rows="10"></textarea>
//

//line web/views/index.html:54
func StreamLog(qw422016 *qt422016.Writer, log string) {
	//line web/views/index.html:54
	qw422016.N().S(`
    <div>`)
	//line web/views/index.html:55
	qw422016.E().S(log)
	//line web/views/index.html:55
	qw422016.N().S(`</div>
`)
//line web/views/index.html:56
}

//line web/views/index.html:56
func WriteLog(qq422016 qtio422016.Writer, log string) {
	//line web/views/index.html:56
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line web/views/index.html:56
	StreamLog(qw422016, log)
	//line web/views/index.html:56
	qt422016.ReleaseWriter(qw422016)
//line web/views/index.html:56
}

//line web/views/index.html:56
func Log(log string) string {
	//line web/views/index.html:56
	qb422016 := qt422016.AcquireByteBuffer()
	//line web/views/index.html:56
	WriteLog(qb422016, log)
	//line web/views/index.html:56
	qs422016 := string(qb422016.B)
	//line web/views/index.html:56
	qt422016.ReleaseByteBuffer(qb422016)
	//line web/views/index.html:56
	return qs422016
//line web/views/index.html:56
}

//line web/views/index.html:58
func StreamJs(qw422016 *qt422016.Writer) {
	//line web/views/index.html:58
	qw422016.N().S(`
$(document).ready(function(){
    $('select').formSelect();
  });

$.post( "ajax/test.html", function( data ) {
    $( ".result" ).html( data );
});

`)
//line web/views/index.html:67
}

//line web/views/index.html:67
func WriteJs(qq422016 qtio422016.Writer) {
	//line web/views/index.html:67
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line web/views/index.html:67
	StreamJs(qw422016)
	//line web/views/index.html:67
	qt422016.ReleaseWriter(qw422016)
//line web/views/index.html:67
}

//line web/views/index.html:67
func Js() string {
	//line web/views/index.html:67
	qb422016 := qt422016.AcquireByteBuffer()
	//line web/views/index.html:67
	WriteJs(qb422016)
	//line web/views/index.html:67
	qs422016 := string(qb422016.B)
	//line web/views/index.html:67
	qt422016.ReleaseByteBuffer(qb422016)
	//line web/views/index.html:67
	return qs422016
//line web/views/index.html:67
}

//line web/views/index.html:69
func StreamStyle(qw422016 *qt422016.Writer) {
	//line web/views/index.html:69
	qw422016.N().S(`
    textarea {
        height: 15rem;
    }
select {
    height: 0;
    padding:0;
    margin:0;
}
`)
//line web/views/index.html:78
}

//line web/views/index.html:78
func WriteStyle(qq422016 qtio422016.Writer) {
	//line web/views/index.html:78
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line web/views/index.html:78
	StreamStyle(qw422016)
	//line web/views/index.html:78
	qt422016.ReleaseWriter(qw422016)
//line web/views/index.html:78
}

//line web/views/index.html:78
func Style() string {
	//line web/views/index.html:78
	qb422016 := qt422016.AcquireByteBuffer()
	//line web/views/index.html:78
	WriteStyle(qb422016)
	//line web/views/index.html:78
	qs422016 := string(qb422016.B)
	//line web/views/index.html:78
	qt422016.ReleaseByteBuffer(qb422016)
	//line web/views/index.html:78
	return qs422016
//line web/views/index.html:78
}
