// This file is automatically generated by qtc from "views.html".
// See https://github.com/valyala/quicktemplate for details.

//line web/views/views.html:1
package views

//line web/views/views.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line web/views/views.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line web/views/views.html:1
func StreamKam(qw422016 *qt422016.Writer, words string, tler string, grams string, tags string) {
	//line web/views/views.html:1
	qw422016.N().S(`

    `)
	//line web/views/views.html:3
	qw422016.E().S(words)
	//line web/views/views.html:3
	qw422016.N().S(`    
    `)
	//line web/views/views.html:4
	qw422016.E().S(tler)
	//line web/views/views.html:4
	qw422016.N().S(`    
    `)
	//line web/views/views.html:5
	qw422016.E().S(grams)
	//line web/views/views.html:5
	qw422016.N().S(`    
    `)
	//line web/views/views.html:6
	qw422016.E().S(tags)
	//line web/views/views.html:6
	qw422016.N().S(`    


`)
//line web/views/views.html:9
}

//line web/views/views.html:9
func WriteKam(qq422016 qtio422016.Writer, words string, tler string, grams string, tags string) {
	//line web/views/views.html:9
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line web/views/views.html:9
	StreamKam(qw422016, words, tler, grams, tags)
	//line web/views/views.html:9
	qt422016.ReleaseWriter(qw422016)
//line web/views/views.html:9
}

//line web/views/views.html:9
func Kam(words string, tler string, grams string, tags string) string {
	//line web/views/views.html:9
	qb422016 := qt422016.AcquireByteBuffer()
	//line web/views/views.html:9
	WriteKam(qb422016, words, tler, grams, tags)
	//line web/views/views.html:9
	qs422016 := string(qb422016.B)
	//line web/views/views.html:9
	qt422016.ReleaseByteBuffer(qb422016)
	//line web/views/views.html:9
	return qs422016
//line web/views/views.html:9
}
